name: gtdclient
description: "GTD client"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0-87.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
