name: gtd_client
description: "FdI GTD App 2024"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.2.6

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.9

  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  crypto: ^3.0.3
  http: ^1.2.0
  go_router: ^13.0.1
  uuid: ^4.3.2
  flutter_secure_storage: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

  build_runner: any
  custom_lint: any
  riverpod_generator: ^2.3.9
  riverpod_lint: ^2.3.7

flutter:
  uses-material-design: true

  assets:
    - assets/svgs/
    - assets/images/
