name: Flutter Web
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build Web
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      
      #- name: Switch Flutter channel
      - run: flutter channel stable && flutter upgrade


      #- name: Install dependencies
      #- run: flutter config --enable-web
      - run: flutter pub get --verbose

      #- name: Build
      - run: flutter build web --release
      - run: |
          cd build/web
          ls -la


   # Subir artefacto
      - uses: actions/upload-artifact@v4
        with:
          name: flutter-web-build
          path: build/web/
